### ISSUE TITLE
Docker Bazel Build Fails

### ISSUE THREAD

**Issue by CandiedCode** [google/ml-metadata#147]
Following the guild for building ml-metadata via docker compose:

`docker-compose build manylinux-python39` or `docker compose build manylinux-python39`
`docker-compose run manylinux-python39` or `docker compose run manylinux-python39`

docker version
```shell
docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I get the following error
```shell
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 2.4 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0.1
    Uninstalling pip-21.0.1:
      Successfully uninstalled pip-21.0.1
Successfully installed pip-22.0.4
Requirement already satisfied: wheel in /opt/_internal/cpython-3.9.2/lib/python3.9/site-packages (0.36.2)
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
  Attempting uninstall: wheel
    Found existing installation: wheel 0.36.2
    Uninstalling wheel-0.36.2:
      Successfully uninstalled wheel-0.36.2
Successfully installed wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting numpy
  Downloading numpy-1.22.3.zip (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.22.3-cp39-cp39-linux_x86_64.whl size=23165600 sha256=4603efc05fcb9e564e0e37b2c77e1bf89122b89eec18b49de34b21af9e83067b
  Stored in directory: /root/.cache/pip/wheels/1b/48/26/7dcbae6a5a0912a3486f7991673eba6fcd8bb87245a067b97f
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.22.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting auditwheel
  Downloading https://files.pythonhosted.org/packages/5e/6d/252b892a851cc43edb523982178da19cf69efc45f5f3aea9752a61813beb/auditwheel-5.1.2-py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 2.6MB/s 
Collecting importlib-metadata; python_version < "3.8" (from auditwheel)
  Downloading https://files.pythonhosted.org/packages/a0/a1/b153a0a4caf7a7e3f15c2cd56c7702e2cf3d89b1b359d1f1c5e59d68f4ce/importlib_metadata-4.8.3-py3-none-any.whl
Collecting pyelftools>=0.24 (from auditwheel)
  Downloading https://files.pythonhosted.org/packages/40/22/6706cc385a099bc5bcb0ea179c2c11863b62c79d37bd47fe464c16f9798d/pyelftools-0.28-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 2.4MB/s 
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->auditwheel)
  Downloading https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->auditwheel)
  Downloading https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Installing collected packages: zipp, typing-extensions, importlib-metadata, pyelftools, auditwheel
Successfully installed auditwheel-5.1.2 importlib-metadata-4.8.3 pyelftools-0.28 typing-extensions-4.1.1 zipp-3.6.0
You are using pip version 9.0.1, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ build_wheel
+ rm -rf dist
+ /opt/python/cp39-cp39/bin/python setup.py bdist_wheel
/opt/python/cp39-cp39/lib/python3.9/site-packages/setuptools/dist.py:463: UserWarning: Normalizing '1.8.0.dev' to '1.8.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running bdist_wheel
running build
running bazel_build
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/624b5d59dfb45672d4239422fa1e3de1822ee110.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository zlib instantiated at:
  /build/WORKSPACE:109:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'zlib':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/zlib/temp4883535670485487851/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/zlib/temp4883535670485487851/zlib-1.2.11.tar.gz: GET returned 404 Not Found
INFO: Repository pybind11 instantiated at:
  /build/WORKSPACE:118:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_google_absl instantiated at:
  /build/WORKSPACE:8:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/com_google_protobuf/BUILD:208:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/zlib/temp4883535670485487851/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//ml_metadata:move_generated_files' failed; build aborted: Analysis failed
INFO: Elapsed time: 62.164s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (32 packages loaded, 644 targets configured)
FAILED: Build did NOT complete successfully (32 packages loaded, 644 targets configured)
Traceback (most recent call last):
  File "/build/setup.py", line 124, in <module>
    setup(
  File "/opt/python/cp39-cp39/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/python/cp39-cp39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp39-cp39/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/build/setup.py", line 102, in run
    subprocess.check_call(
  File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bazel', 'run', '--compilation_mode', 'opt', '--define', 'grpc_no_ares=true', '--verbose_failures', '//ml_metadata:move_generated_files']' returned non-zero exit status 1.

**Comment by CandiedCode** [comment]
Looks like zlib 1.2.12 was released March 27, 2022, and https://zlib.net/zlib-1.2.11.tar.gz is no longer available.

**Comment by CandiedCode** [comment]
docker build/run is working after zlib bazel update.  Closing issue.
