### ISSUE TITLE
mysql setup for ml-metadata

### ISSUE THREAD

**Issue by CandiedCode** [google/ml-metadata#149]
Hello,

I'm hoping someone can provide some guidance.  I've tried to setup a quick example of connecting ml-metadata  to a mysql database running locally.

I've tried on my mac as well as via docker containers incase it was a mac/mysql c connector issue.  Both cases I get the same error message.

```shell
Traceback (most recent call last):
  File "/code/ml_metadata_playground/metadata.py", line 44, in <module>
    store = connect_mysql()
  File "/code/ml_metadata_playground/metadata.py", line 17, in connect_mysql
    return metadata_store.MetadataStore(connection_config)
  File "/usr/local/lib/python3.9/dist-packages/ml_metadata/metadata_store/metadata_store.py", line 103, in __init__
    self._metadata_store = metadata_store_serialized.CreateMetadataStore(
RuntimeError: mysql_real_connect failed: errno: , error: 
```

For my mac:
I'm using python3.9 nightly build
- "https://pypi-nightly.tensorflow.org/api/package/ml-metadata/ml_metadata-1.8.0.dev20220327-cp39-cp39-macosx_10_14_x86_64.whl#sha256=01f6d117e60a515ac46d93ccff36a2f63972e4c7a81eb35bba40e1ec61313bd3"
- have `mysql-client` (replaces mysql-connector-c) via brew install and `mariadb-connector-c` via brew as well

The full error via this pytest
```shell
self = <ml_metadata.metadata_store.metadata_store.MetadataStore object at 0x7f980ad70be0>
config = mysql {
  host: "0.0.0.0"
  port: 3306
  database: "metadata"
  user: "test"
  password: "secret"
}
, enable_upgrade_migration = True

    def __init__(self,
                 config: Union[proto.ConnectionConfig,
                               proto.MetadataStoreClientConfig],
                 enable_upgrade_migration: bool = False):
      """Initialize the MetadataStore.

      MetadataStore can directly connect to either the metadata database or
      the MLMD MetadataStore gRPC server.

      Args:
        config: `proto.ConnectionConfig` or `proto.MetadataStoreClientConfig`.
          Configuration to connect to the database or the metadata store server.
        enable_upgrade_migration: if set to True, the library upgrades the db
          schema and migrates all data if it connects to an old version backend.
          It is ignored when using gRPC `proto.MetadataStoreClientConfig`.
      """
      self._max_num_retries = 5
      if isinstance(config, proto.ConnectionConfig):
        self._using_db_connection = True
        migration_options = metadata_store_pb2.MigrationOptions()
        migration_options.enable_upgrade_migration = enable_upgrade_migration
>       self._metadata_store = metadata_store_serialized.CreateMetadataStore(
            config.SerializeToString(), migration_options.SerializeToString())
E       RuntimeError: mysql_real_connect failed: errno: , error:
```

I've tried to quickly create a dummy repo to share what my images look like via docker-compose via https://github.com/CandiedCode/ml-metadata-playground/blob/mysql_test/ml_metadata_playground/metadata.py#L42
https://github.com/CandiedCode/ml-metadata-playground/blob/mysql_test/docker-compose.yaml

```shell
docker compose run meta
[+] Running 1/0
 ⠿ Container ml-metadata-playground-db-1  Run...                                         0.0s
Traceback (most recent call last):
  File "/code/ml_metadata_playground/metadata.py", line 44, in <module>
    store = connect_mysql()
  File "/code/ml_metadata_playground/metadata.py", line 17, in connect_mysql
    return metadata_store.MetadataStore(connection_config)
  File "/usr/local/lib/python3.9/dist-packages/ml_metadata/metadata_store/metadata_store.py", line 103, in __init__
    self._metadata_store = metadata_store_serialized.CreateMetadataStore(
RuntimeError: mysql_real_connect failed: errno: , error: 
```

Not sure if this is an issue with the nightly 3.9 build or my local MySQL c driver setup.

**Comment by CandiedCode** [comment]
created https://github.com/google/ml-metadata/pull/150 to test local wheel package for python 3.9

**Comment by BrianSong** [comment]
Are you using Azure MySQL?

Also, could you try "127.0.0.1" instead of "0.0.0.0" for your local host?

**Comment by CandiedCode** [comment]
I'm just running a mysql docker container in my same network via docker-compose.

I've tried both 0.0.0.0:3306 when running python locally and then also 'db:3306' when running inside `docker compose`.
```python
def connect_mysql() -> metadata_store.MetadataStore:
    connection_config = metadata_store_pb2.ConnectionConfig()
    connection_config.mysql.host = '0.0.0.0'. # use 0.0.0.0 when running python file locally, or 'db' when running via docker-compose
    connection_config.mysql.port = 3306
    connection_config.mysql.database = 'metadata'
    connection_config.mysql.user = 'test'
    connection_config.mysql.password = 'secret'
    return metadata_store.MetadataStore(connection_config)
```

```
version: "3.9"
services:
  meta:
    build: .
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'metadata'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  ```

# libraries install in dockerfile
```shell
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.8 python3.8-dev python3-pip libssl-dev libmysqlclient-dev mysql-client
```

via local shell
```shell
mysql --host=0.0.0.0 --port=3306 --user=test --password=secret  metadata
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.28 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
inside the docker container, i use the service name since '0.0.0.0' doesn't work
```shell
# inside the meta docker container
mysql --host=db --port=3306 --user=test --password=secret  metadata
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 13
Server version: 8.0.28 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

  
Since the error message isn't descriptive, I feel like I'm missing something in my dockerfile for the python script for running the mysql connect c library.  🤷🏽‍♀️  maybe.

**Comment by CandiedCode** [comment]
Thanks @GerardoGR 

That did solve my issue.
